name: responsive
description: Allow to easily build a responsive Flutter UI
version: 0.1.3
author: Marvin O. Quevedo<osielquevedo@gmail.com>
homepage: https://github.com/flutter-es/responsive

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
